call compile.bat bean\*.java
call compile.bat dao\*.java
call compile.bat tool\*.java
call compile.bat chapter3\*.java
call compile.bat chapter4\*.java
call compile.bat chapter5\*.java
call compile.bat chapter6\*.java
call compile.bat chapter9\*.java
call compile.bat chapter10\*.java
call compile.bat chapter11\*.java
call compile.bat chapter12\*.java
call compile.bat chapter14\*.java
call compile.bat chapter15\*.java
call compile.bat chapter16\*.java
call compile.bat chapter17\*.java
call compile.bat chapter18\*.java
call compile.bat chapter19\*.java
call compile.bat chapter20\*.java
call compile.bat chapter21\*.java
call compile.bat chapter22\*.java
call compile.bat chapter23\*.java
call compile.bat chapter24\*.java
call compile.bat chapter25\*.java
